spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
project:
  poster: posters/
base:
  url: "http://localhost:8080"
